### ISSUE TITLE
Juno-6 error ??

### ISSUE THREAD

**Issue by roman65536** [shorepine/tulipcc#373]
Hi, 

Yesterday I downloaded and compiled Tulip, since the I get following error when try to run Juno-6:

>>> run("juno6")
Problem running juno6: 
Traceback (most recent call last):
  File "tulip.py", line 535, in run
  File "<string>", line 1, in <module>
  File "juno6.py", line 532, in <module>
  File "juno6.py", line 510, in get_active_midi_channels_as_str
  File "midi.py", line 75, in channel_info
AttributeError: 'DrumSynth' object has no attribute 'patch_number'
>>> 

rgds
Roman

**Comment by bwhitman** [comment]
Fixed (for me) by #374. give it a go again, thanks!
